FROM golang:1.24-alpine

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .
COPY entry-point-test.sh /app/entry-point-test.sh
RUN cp .env.docker.development .env
RUN chmod +x entry-point-test.sh

ENTRYPOINT ["/app/entry-point-test.sh"]


